"use client";
import { useEffect, useMemo, useState } from "react";

type Anime={id:number;year:number;title:string;genres:string[];rank:"S"|"A"|"B"|"C";note:string;watch:boolean};
const decades=["全部","1960—79","1980s","1990s","2000s","2010s","2020s"];
const colors=["blue","yellow","coral","mint"];
function decadeMatch(year:number,label:string){if(label==="全部")return true;if(label==="1960—79")return year<1980;return Math.floor(year/10)*10===Number(label.slice(0,4));}

export default function Home(){
 const[anime,setAnime]=useState<Anime[]>([]),[query,setQuery]=useState(""),[decade,setDecade]=useState("全部"),[rank,setRank]=useState("全部级别"),[genre,setGenre]=useState("全部类型");const[limit,setLimit]=useState(18);const[watchFilter,setWatchFilter]=useState("全部作品");const[watched,setWatched]=useState<Set<number>>(new Set());const[ready,setReady]=useState(false);
 useEffect(()=>{fetch("/anime.json").then(r=>r.json()).then(setAnime)},[]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("anime-panorama-watched")||"[]");setWatched(new Set(saved))}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready)localStorage.setItem("anime-panorama-watched",JSON.stringify([...watched]))},[watched,ready]);
 const genres=useMemo(()=>{const c=new Map<string,number>();anime.forEach(i=>i.genres.forEach(t=>c.set(t,(c.get(t)||0)+1)));return[...c.entries()].sort((a,b)=>b[1]-a[1]).slice(0,18).map(x=>x[0])},[anime]);
 const filtered=useMemo(()=>anime.filter(i=>`${i.title} ${i.note} ${i.genres.join(" ")}`.toLowerCase().includes(query.toLowerCase())&&decadeMatch(i.year,decade)&&(rank==="全部级别"||i.rank===rank)&&(genre==="全部类型"||i.genres.includes(genre))&&(watchFilter==="全部作品"||(watchFilter==="已看"?watched.has(i.id):!watched.has(i.id)))),[anime,query,decade,rank,genre,watchFilter,watched]);
 const reset=()=>{setQuery("");setDecade("全部");setRank("全部级别");setGenre("全部类型");setWatchFilter("全部作品");setLimit(18)};
 const toggleWatched=(id:number)=>setWatched(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
 const watchedDecades=new Set(anime.filter(i=>watched.has(i.id)).map(i=>Math.floor(i.year/10)*10)).size;
 const randomUnseen=()=>{const pool=anime.filter(i=>!watched.has(i.id));if(!pool.length)return;const pick=pool[Math.floor(Math.random()*pool.length)];setQuery(pick.title);setWatchFilter("全部作品");setDecade("全部");setRank("全部级别");setGenre("全部类型");setLimit(18)};
 return <main>
  <header className="site-header"><a className="brand" href="#top" aria-label="动画全景首页"><span>ANIME</span><b>PANORAMA</b></a><nav aria-label="主导航"><a className="active" href="#top">总览</a><a href="#archive">目录</a><a href="#method">方法</a><a href="https://github.com/aiiierrrr16-art" target="_blank" rel="noreferrer">GitHub ↗</a></nav><a className="header-cta" href="#archive">开始探索 ↘</a></header>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">日本动画文化档案 · EST. 1963</p><h1>一张跨越<br/><em>六十年</em>的<br/>动画文化地图</h1><p className="hero-intro">从电视动画黎明，到OVA黄金期与流媒体时代。不是评分榜，而是按年代、类型与影响力整理的日本动画全景目录。</p><a className="button mint" href="#archive">浏览完整目录 <span>→</span></a></div><div className="hero-board" aria-label="目录关键统计"><div className="stat blue"><strong>393</strong><span>部／系列</span></div><div className="stat coral"><strong>64</strong><span>年跨度</span></div><div className="stat mint"><strong>70+</strong><span>类型标签</span></div><div className="stat yellow"><strong>S—C</strong><span>影响力分级</span></div><div className="stamp">ARCHIVE<br/>NO. 001</div></div></section>
  <div className="marquee" aria-hidden="true"><div>国民动画 ★ 作者表达 ★ 类型革命 ★ 全球传播 ★ 时代记忆 ★ 国民动画 ★ 作者表达 ★ 类型革命 ★ 全球传播 ★ 时代记忆 ★</div></div>
  <section className="archive" id="archive"><div className="section-heading light"><span>01 / THE ARCHIVE</span><h2>探索全部作品</h2><p>搜索作品名或入选理由，也可以组合年代、类型和影响力级别。</p></div>
   <div className="watch-dashboard"><div className="watch-score"><span>我的观看档案</span><strong>{watched.size}<small> / 393</small></strong><p>已看过 · {anime.length?Math.round(watched.size/anime.length*100):0}%</p></div><div className="watch-progress"><div><span style={{width:`${anime.length?watched.size/anime.length*100:0}%`}}/></div><p><b>{watchedDecades}</b> 个年代已覆盖　·　<b>{anime.filter(i=>i.rank==="S"&&watched.has(i.id)).length}</b> 部 S 级已看</p></div><button onClick={randomUnseen}>随机挑一部未看 ↗</button></div>
   <div className="filters"><label className="search"><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setLimit(18)}} placeholder="搜索作品、类型或关键词…" aria-label="搜索目录"/></label><select value={genre} onChange={e=>{setGenre(e.target.value);setLimit(18)}} aria-label="按类型筛选"><option>全部类型</option>{genres.map(x=><option key={x}>{x}</option>)}</select><select value={rank} onChange={e=>{setRank(e.target.value);setLimit(18)}} aria-label="按级别筛选"><option>全部级别</option><option>S</option><option>A</option><option>B</option><option>C</option></select></div>
   <div className="watch-tabs" aria-label="观看状态筛选">{["全部作品","未看","已看"].map(x=><button className={watchFilter===x?"selected":""} onClick={()=>{setWatchFilter(x);setLimit(18)}} key={x}>{x}{x==="已看"&&` ${watched.size}`}</button>)}</div>
   <div className="decade-tabs" aria-label="按年代筛选">{decades.map(x=><button className={decade===x?"selected":""} onClick={()=>{setDecade(x);setLimit(18)}} key={x}>{x}</button>)}</div><div className="results-bar"><b>{filtered.length}</b> 条结果 <span>· 勾选会自动保存在本设备</span><button onClick={reset}>清除筛选 ×</button></div>
   <div className="anime-grid">{filtered.slice(0,limit).map((item,index)=><article className={`anime-card ${colors[index%4]} ${watched.has(item.id)?"is-watched":""}`} key={item.id}><div className="card-top"><span>{String(item.id).padStart(3,"0")}</span><b className={`rank rank-${item.rank.toLowerCase()}`}>{item.rank}</b></div><div><p className="year">{item.year}{item.watch&&<i>观察中</i>}</p><h3>{item.title}</h3><div className="tags">{item.genres.map(t=><span key={t}>{t}</span>)}</div><p className="note">{item.note}</p><div className="card-actions"><button className="watched-toggle" aria-pressed={watched.has(item.id)} onClick={()=>toggleWatched(item.id)}><span>{watched.has(item.id)?"✓":""}</span>{watched.has(item.id)?"已经看过":"标记为看过"}</button><a className="google-link" href={`https://www.google.com/search?q=${encodeURIComponent(`${item.title} 日本动画 百科`)}`} target="_blank" rel="noreferrer" aria-label={`在Google查看${item.title}的百科资料`}>Google 百科资料 ↗</a></div></div></article>)}</div>
   {!anime.length&&<p className="loading">正在展开档案…</p>}{!!anime.length&&!filtered.length&&<div className="empty"><strong>没有匹配项</strong><p>换一个关键词，或清除部分筛选条件。</p><button onClick={reset}>重置目录</button></div>}{limit<filtered.length&&<button className="load-more" onClick={()=>setLimit(limit+18)}>继续展开 · {filtered.length-limit} 条待查看 ↓</button>}
  </section>
  <section className="method" id="method"><div><span>02 / METHOD</span><h2>这不是<br/>评分排行榜。</h2></div><div className="method-copy"><p>入选依据综合日本本土认知、海外传播、商业影响、类型创新、创作者影响与长期口碑。系列原则上合并；独立历史意义明确的电影或版本单列。</p><div className="rank-list"><b>S 世界级／改变类型</b><b>A 现象级／一线名作</b><b>B 类型经典／圈层核心</b><b>C 特定时期的重要补充</b></div><small>2025—2026年的新作标记为“观察中”，历史地位将持续复核。</small></div></section>
  <footer><div className="brand footer-brand"><span>ANIME</span><b>PANORAMA</b></div><p>日本知名动漫全景目录<br/>版本 2026.08.29</p><div className="footer-links"><a href="https://github.com/aiiierrrr16-art" target="_blank" rel="noreferrer">GitHub ↗</a><a href="#top">回到顶部 ↑</a></div></footer>
 </main>
}
